// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientProtocolProto.proto

package protobuf;

public final class ClientProtocolProto {
  private ClientProtocolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 groupNum = 1;
    /**
     * <code>required int32 groupNum = 1;</code>
     */
    boolean hasGroupNum();
    /**
     * <code>required int32 groupNum = 1;</code>
     */
    int getGroupNum();

    // required string sign = 2;
    /**
     * <code>required string sign = 2;</code>
     */
    boolean hasSign();
    /**
     * <code>required string sign = 2;</code>
     */
    String getSign();
    /**
     * <code>required string sign = 2;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();

    // required string playerId = 3;
    /**
     * <code>required string playerId = 3;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required string playerId = 3;</code>
     */
    String getPlayerId();
    /**
     * <code>required string playerId = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    // required string order = 4;
    /**
     * <code>required string order = 4;</code>
     */
    boolean hasOrder();
    /**
     * <code>required string order = 4;</code>
     */
    String getOrder();
    /**
     * <code>required string order = 4;</code>
     */
    com.google.protobuf.ByteString
        getOrderBytes();
  }
  /**
   * Protobuf type {@code netty.ClientProtocol}
   */
  public static final class ClientProtocol extends
      com.google.protobuf.GeneratedMessage
      implements ClientProtocolOrBuilder {
    // Use ClientProtocol.newBuilder() to construct.
    private ClientProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientProtocol defaultInstance;
    public static ClientProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public ClientProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              groupNum_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sign_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              playerId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              order_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientProtocolProto.internal_static_netty_ClientProtocol_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientProtocolProto.internal_static_netty_ClientProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientProtocol.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ClientProtocol> PARSER =
        new com.google.protobuf.AbstractParser<ClientProtocol>() {
      public ClientProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientProtocol(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ClientProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 groupNum = 1;
    public static final int GROUPNUM_FIELD_NUMBER = 1;
    private int groupNum_;
    /**
     * <code>required int32 groupNum = 1;</code>
     */
    public boolean hasGroupNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 groupNum = 1;</code>
     */
    public int getGroupNum() {
      return groupNum_;
    }

    // required string sign = 2;
    public static final int SIGN_FIELD_NUMBER = 2;
    private Object sign_;
    /**
     * <code>required string sign = 2;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sign = 2;</code>
     */
    public String getSign() {
      Object ref = sign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sign = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string playerId = 3;
    public static final int PLAYERID_FIELD_NUMBER = 3;
    private Object playerId_;
    /**
     * <code>required string playerId = 3;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string playerId = 3;</code>
     */
    public String getPlayerId() {
      Object ref = playerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string playerId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      Object ref = playerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string order = 4;
    public static final int ORDER_FIELD_NUMBER = 4;
    private Object order_;
    /**
     * <code>required string order = 4;</code>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string order = 4;</code>
     */
    public String getOrder() {
      Object ref = order_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          order_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string order = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOrderBytes() {
      Object ref = order_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        order_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      groupNum_ = 0;
      sign_ = "";
      playerId_ = "";
      order_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGroupNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, groupNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSignBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPlayerIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getOrderBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, groupNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSignBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPlayerIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getOrderBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.ClientProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ClientProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientProtocolProto.internal_static_netty_ClientProtocol_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientProtocolProto.internal_static_netty_ClientProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientProtocol.class, Builder.class);
      }

      // Construct using protobuf.ClientProtocolProto.ClientProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        order_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientProtocolProto.internal_static_netty_ClientProtocol_descriptor;
      }

      public ClientProtocol getDefaultInstanceForType() {
        return ClientProtocol.getDefaultInstance();
      }

      public ClientProtocol build() {
        ClientProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientProtocol buildPartial() {
        ClientProtocol result = new ClientProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupNum_ = groupNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sign_ = sign_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.order_ = order_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientProtocol) {
          return mergeFrom((ClientProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientProtocol other) {
        if (other == ClientProtocol.getDefaultInstance()) return this;
        if (other.hasGroupNum()) {
          setGroupNum(other.getGroupNum());
        }
        if (other.hasSign()) {
          bitField0_ |= 0x00000002;
          sign_ = other.sign_;
          onChanged();
        }
        if (other.hasPlayerId()) {
          bitField0_ |= 0x00000004;
          playerId_ = other.playerId_;
          onChanged();
        }
        if (other.hasOrder()) {
          bitField0_ |= 0x00000008;
          order_ = other.order_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGroupNum()) {
          
          return false;
        }
        if (!hasSign()) {
          
          return false;
        }
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasOrder()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 groupNum = 1;
      private int groupNum_ ;
      /**
       * <code>required int32 groupNum = 1;</code>
       */
      public boolean hasGroupNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 groupNum = 1;</code>
       */
      public int getGroupNum() {
        return groupNum_;
      }
      /**
       * <code>required int32 groupNum = 1;</code>
       */
      public Builder setGroupNum(int value) {
        bitField0_ |= 0x00000001;
        groupNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 groupNum = 1;</code>
       */
      public Builder clearGroupNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupNum_ = 0;
        onChanged();
        return this;
      }

      // required string sign = 2;
      private Object sign_ = "";
      /**
       * <code>required string sign = 2;</code>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public String getSign() {
        Object ref = sign_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public Builder setSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 2;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sign_ = value;
        onChanged();
        return this;
      }

      // required string playerId = 3;
      private Object playerId_ = "";
      /**
       * <code>required string playerId = 3;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string playerId = 3;</code>
       */
      public String getPlayerId() {
        Object ref = playerId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string playerId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string playerId = 3;</code>
       */
      public Builder setPlayerId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string playerId = 3;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        playerId_ = getDefaultInstance().getPlayerId();
        onChanged();
        return this;
      }
      /**
       * <code>required string playerId = 3;</code>
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        playerId_ = value;
        onChanged();
        return this;
      }

      // required string order = 4;
      private Object order_ = "";
      /**
       * <code>required string order = 4;</code>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string order = 4;</code>
       */
      public String getOrder() {
        Object ref = order_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          order_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string order = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOrderBytes() {
        Object ref = order_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          order_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string order = 4;</code>
       */
      public Builder setOrder(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string order = 4;</code>
       */
      public Builder clearOrder() {
        bitField0_ = (bitField0_ & ~0x00000008);
        order_ = getDefaultInstance().getOrder();
        onChanged();
        return this;
      }
      /**
       * <code>required string order = 4;</code>
       */
      public Builder setOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        order_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.ClientProtocol)
    }

    static {
      defaultInstance = new ClientProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.ClientProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_ClientProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_ClientProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031clientProtocolProto.proto\022\005netty\"Q\n\016Cl" +
      "ientProtocol\022\020\n\010groupNum\030\001 \002(\005\022\014\n\004sign\030\002" +
      " \002(\t\022\020\n\010playerId\030\003 \002(\t\022\r\n\005order\030\004 \002(\tB\037\n" +
      "\010protobufB\023ClientProtocolProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_netty_ClientProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_netty_ClientProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netty_ClientProtocol_descriptor,
              new String[] { "GroupNum", "Sign", "PlayerId", "Order", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
