// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverProtocolProto.proto

package protobuf;

public final class ServerProtocolProto {
  private ServerProtocolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string sign = 1;
    /**
     * <code>required string sign = 1;</code>
     */
    boolean hasSign();
    /**
     * <code>required string sign = 1;</code>
     */
    String getSign();
    /**
     * <code>required string sign = 1;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();

    // required string playerId = 2;
    /**
     * <code>required string playerId = 2;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required string playerId = 2;</code>
     */
    String getPlayerId();
    /**
     * <code>required string playerId = 2;</code>
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    // required int32 x = 3;
    /**
     * <code>required int32 x = 3;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 3;</code>
     */
    int getX();

    // required int32 y = 4;
    /**
     * <code>required int32 y = 4;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 4;</code>
     */
    int getY();

    // required int32 direction = 5;
    /**
     * <code>required int32 direction = 5;</code>
     */
    boolean hasDirection();
    /**
     * <code>required int32 direction = 5;</code>
     */
    int getDirection();

    // required int32 lives = 6;
    /**
     * <code>required int32 lives = 6;</code>
     */
    boolean hasLives();
    /**
     * <code>required int32 lives = 6;</code>
     */
    int getLives();

    // required int32 health = 7;
    /**
     * <code>required int32 health = 7;</code>
     */
    boolean hasHealth();
    /**
     * <code>required int32 health = 7;</code>
     */
    int getHealth();

    // required int32 score = 8;
    /**
     * <code>required int32 score = 8;</code>
     */
    boolean hasScore();
    /**
     * <code>required int32 score = 8;</code>
     */
    int getScore();

    // required int32 strength = 9;
    /**
     * <code>required int32 strength = 9;</code>
     */
    boolean hasStrength();
    /**
     * <code>required int32 strength = 9;</code>
     */
    int getStrength();

    // required int32 respawnCounter = 10;
    /**
     * <code>required int32 respawnCounter = 10;</code>
     */
    boolean hasRespawnCounter();
    /**
     * <code>required int32 respawnCounter = 10;</code>
     */
    int getRespawnCounter();
  }
  /**
   * Protobuf type {@code netty.ServerProtocol}
   */
  public static final class ServerProtocol extends
      com.google.protobuf.GeneratedMessage
      implements ServerProtocolOrBuilder {
    // Use ServerProtocol.newBuilder() to construct.
    private ServerProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerProtocol defaultInstance;
    public static ServerProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public ServerProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sign_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              playerId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              x_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              y_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              direction_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              lives_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              health_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              score_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              strength_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              respawnCounter_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerProtocolProto.internal_static_netty_ServerProtocol_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerProtocolProto.internal_static_netty_ServerProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerProtocol.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ServerProtocol> PARSER =
        new com.google.protobuf.AbstractParser<ServerProtocol>() {
      public ServerProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerProtocol(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ServerProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string sign = 1;
    public static final int SIGN_FIELD_NUMBER = 1;
    private Object sign_;
    /**
     * <code>required string sign = 1;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sign = 1;</code>
     */
    public String getSign() {
      Object ref = sign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sign = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string playerId = 2;
    public static final int PLAYERID_FIELD_NUMBER = 2;
    private Object playerId_;
    /**
     * <code>required string playerId = 2;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string playerId = 2;</code>
     */
    public String getPlayerId() {
      Object ref = playerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string playerId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      Object ref = playerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 x = 3;
    public static final int X_FIELD_NUMBER = 3;
    private int x_;
    /**
     * <code>required int32 x = 3;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 x = 3;</code>
     */
    public int getX() {
      return x_;
    }

    // required int32 y = 4;
    public static final int Y_FIELD_NUMBER = 4;
    private int y_;
    /**
     * <code>required int32 y = 4;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 y = 4;</code>
     */
    public int getY() {
      return y_;
    }

    // required int32 direction = 5;
    public static final int DIRECTION_FIELD_NUMBER = 5;
    private int direction_;
    /**
     * <code>required int32 direction = 5;</code>
     */
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 direction = 5;</code>
     */
    public int getDirection() {
      return direction_;
    }

    // required int32 lives = 6;
    public static final int LIVES_FIELD_NUMBER = 6;
    private int lives_;
    /**
     * <code>required int32 lives = 6;</code>
     */
    public boolean hasLives() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 lives = 6;</code>
     */
    public int getLives() {
      return lives_;
    }

    // required int32 health = 7;
    public static final int HEALTH_FIELD_NUMBER = 7;
    private int health_;
    /**
     * <code>required int32 health = 7;</code>
     */
    public boolean hasHealth() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 health = 7;</code>
     */
    public int getHealth() {
      return health_;
    }

    // required int32 score = 8;
    public static final int SCORE_FIELD_NUMBER = 8;
    private int score_;
    /**
     * <code>required int32 score = 8;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 score = 8;</code>
     */
    public int getScore() {
      return score_;
    }

    // required int32 strength = 9;
    public static final int STRENGTH_FIELD_NUMBER = 9;
    private int strength_;
    /**
     * <code>required int32 strength = 9;</code>
     */
    public boolean hasStrength() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 strength = 9;</code>
     */
    public int getStrength() {
      return strength_;
    }

    // required int32 respawnCounter = 10;
    public static final int RESPAWNCOUNTER_FIELD_NUMBER = 10;
    private int respawnCounter_;
    /**
     * <code>required int32 respawnCounter = 10;</code>
     */
    public boolean hasRespawnCounter() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 respawnCounter = 10;</code>
     */
    public int getRespawnCounter() {
      return respawnCounter_;
    }

    private void initFields() {
      sign_ = "";
      playerId_ = "";
      x_ = 0;
      y_ = 0;
      direction_ = 0;
      lives_ = 0;
      health_ = 0;
      score_ = 0;
      strength_ = 0;
      respawnCounter_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDirection()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLives()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHealth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStrength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRespawnCounter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSignBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPlayerIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, direction_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, lives_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, health_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, score_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, strength_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, respawnCounter_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSignBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPlayerIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, direction_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, lives_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, health_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, score_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, strength_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, respawnCounter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ServerProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ServerProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ServerProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ServerProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ServerProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ServerProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ServerProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.ServerProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ServerProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerProtocolProto.internal_static_netty_ServerProtocol_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerProtocolProto.internal_static_netty_ServerProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerProtocol.class, Builder.class);
      }

      // Construct using protobuf.ServerProtocolProto.ServerProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        direction_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        lives_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        health_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        strength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        respawnCounter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServerProtocolProto.internal_static_netty_ServerProtocol_descriptor;
      }

      public ServerProtocol getDefaultInstanceForType() {
        return ServerProtocol.getDefaultInstance();
      }

      public ServerProtocol build() {
        ServerProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ServerProtocol buildPartial() {
        ServerProtocol result = new ServerProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sign_ = sign_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.direction_ = direction_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.lives_ = lives_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.health_ = health_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.strength_ = strength_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.respawnCounter_ = respawnCounter_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServerProtocol) {
          return mergeFrom((ServerProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServerProtocol other) {
        if (other == ServerProtocol.getDefaultInstance()) return this;
        if (other.hasSign()) {
          bitField0_ |= 0x00000001;
          sign_ = other.sign_;
          onChanged();
        }
        if (other.hasPlayerId()) {
          bitField0_ |= 0x00000002;
          playerId_ = other.playerId_;
          onChanged();
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasDirection()) {
          setDirection(other.getDirection());
        }
        if (other.hasLives()) {
          setLives(other.getLives());
        }
        if (other.hasHealth()) {
          setHealth(other.getHealth());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasStrength()) {
          setStrength(other.getStrength());
        }
        if (other.hasRespawnCounter()) {
          setRespawnCounter(other.getRespawnCounter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSign()) {
          
          return false;
        }
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasDirection()) {
          
          return false;
        }
        if (!hasLives()) {
          
          return false;
        }
        if (!hasHealth()) {
          
          return false;
        }
        if (!hasScore()) {
          
          return false;
        }
        if (!hasStrength()) {
          
          return false;
        }
        if (!hasRespawnCounter()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServerProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServerProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string sign = 1;
      private Object sign_ = "";
      /**
       * <code>required string sign = 1;</code>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public String getSign() {
        Object ref = sign_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public Builder setSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sign_ = value;
        onChanged();
        return this;
      }

      // required string playerId = 2;
      private Object playerId_ = "";
      /**
       * <code>required string playerId = 2;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string playerId = 2;</code>
       */
      public String getPlayerId() {
        Object ref = playerId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string playerId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string playerId = 2;</code>
       */
      public Builder setPlayerId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string playerId = 2;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = getDefaultInstance().getPlayerId();
        onChanged();
        return this;
      }
      /**
       * <code>required string playerId = 2;</code>
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }

      // required int32 x = 3;
      private int x_ ;
      /**
       * <code>required int32 x = 3;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000004;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0;
        onChanged();
        return this;
      }

      // required int32 y = 4;
      private int y_ ;
      /**
       * <code>required int32 y = 4;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000008;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y_ = 0;
        onChanged();
        return this;
      }

      // required int32 direction = 5;
      private int direction_ ;
      /**
       * <code>required int32 direction = 5;</code>
       */
      public boolean hasDirection() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 direction = 5;</code>
       */
      public int getDirection() {
        return direction_;
      }
      /**
       * <code>required int32 direction = 5;</code>
       */
      public Builder setDirection(int value) {
        bitField0_ |= 0x00000010;
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 direction = 5;</code>
       */
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000010);
        direction_ = 0;
        onChanged();
        return this;
      }

      // required int32 lives = 6;
      private int lives_ ;
      /**
       * <code>required int32 lives = 6;</code>
       */
      public boolean hasLives() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 lives = 6;</code>
       */
      public int getLives() {
        return lives_;
      }
      /**
       * <code>required int32 lives = 6;</code>
       */
      public Builder setLives(int value) {
        bitField0_ |= 0x00000020;
        lives_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lives = 6;</code>
       */
      public Builder clearLives() {
        bitField0_ = (bitField0_ & ~0x00000020);
        lives_ = 0;
        onChanged();
        return this;
      }

      // required int32 health = 7;
      private int health_ ;
      /**
       * <code>required int32 health = 7;</code>
       */
      public boolean hasHealth() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 health = 7;</code>
       */
      public int getHealth() {
        return health_;
      }
      /**
       * <code>required int32 health = 7;</code>
       */
      public Builder setHealth(int value) {
        bitField0_ |= 0x00000040;
        health_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 health = 7;</code>
       */
      public Builder clearHealth() {
        bitField0_ = (bitField0_ & ~0x00000040);
        health_ = 0;
        onChanged();
        return this;
      }

      // required int32 score = 8;
      private int score_ ;
      /**
       * <code>required int32 score = 8;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 score = 8;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>required int32 score = 8;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000080;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 score = 8;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000080);
        score_ = 0;
        onChanged();
        return this;
      }

      // required int32 strength = 9;
      private int strength_ ;
      /**
       * <code>required int32 strength = 9;</code>
       */
      public boolean hasStrength() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 strength = 9;</code>
       */
      public int getStrength() {
        return strength_;
      }
      /**
       * <code>required int32 strength = 9;</code>
       */
      public Builder setStrength(int value) {
        bitField0_ |= 0x00000100;
        strength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 strength = 9;</code>
       */
      public Builder clearStrength() {
        bitField0_ = (bitField0_ & ~0x00000100);
        strength_ = 0;
        onChanged();
        return this;
      }

      // required int32 respawnCounter = 10;
      private int respawnCounter_ ;
      /**
       * <code>required int32 respawnCounter = 10;</code>
       */
      public boolean hasRespawnCounter() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 respawnCounter = 10;</code>
       */
      public int getRespawnCounter() {
        return respawnCounter_;
      }
      /**
       * <code>required int32 respawnCounter = 10;</code>
       */
      public Builder setRespawnCounter(int value) {
        bitField0_ |= 0x00000200;
        respawnCounter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 respawnCounter = 10;</code>
       */
      public Builder clearRespawnCounter() {
        bitField0_ = (bitField0_ & ~0x00000200);
        respawnCounter_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.ServerProtocol)
    }

    static {
      defaultInstance = new ServerProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.ServerProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_ServerProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_ServerProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031serverProtocolProto.proto\022\005netty\"\261\001\n\016S" +
      "erverProtocol\022\014\n\004sign\030\001 \002(\t\022\020\n\010playerId\030" +
      "\002 \002(\t\022\t\n\001x\030\003 \002(\005\022\t\n\001y\030\004 \002(\005\022\021\n\tdirection" +
      "\030\005 \002(\005\022\r\n\005lives\030\006 \002(\005\022\016\n\006health\030\007 \002(\005\022\r\n" +
      "\005score\030\010 \002(\005\022\020\n\010strength\030\t \002(\005\022\026\n\016respaw" +
      "nCounter\030\n \002(\005B\037\n\010protobufB\023ServerProtoc" +
      "olProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_netty_ServerProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_netty_ServerProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netty_ServerProtocol_descriptor,
              new String[] { "Sign", "PlayerId", "X", "Y", "Direction", "Lives", "Health", "Score", "Strength", "RespawnCounter", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
